version: '3'
services:
  web:
    build: .
    ports:
    - "8888:5000"
    depends_on:
    - redis
    - slurm

  redis:
    image: redis
    ports:
        - "6379:6379"

  slurm:
      build: slurm_test/
