DB_Table             = 't_bumps_jobs'
DB_Field_JobID       = 'job_id'
DB_Field_SentIP      = 'sent_ip'
DB_Field_SentTime    = 'sent_time'
DB_Field_Tag         = 'tag'
DB_Field_Message     = 'message'
DB_Field_ResultsDir  = 'results_dir'
DB_Field_ProblemFile = 'problem_file'
DB_Field_JobStatus   = 'job_status'
DB_Field_EndTime     = 'end_time'

DB_StatusTable      = 't_jobs_status'
DB_Field_StatusTime = 'status_time'
DB_Field_StatusName = 'status_name'

