tbl_bumps_jobs   = 't_bumps_jobs'
fld_JobID        = 'job_id'
fld_SentIP       = 'sent_ip'
fld_SentTime     = 'sent_time'
fld_Tag          = 'tag'
fld_Message      = 'message'
fld_Fitter       = 'fitter'
fld_ResultsDir   = 'results_dir'
fld_ProblemFile  = 'problem_file'
fld_JobStatus    = 'job_status'
fld_EndTime      = 'end_time'
fld_chi_sqaue    =  'chi_square'
fld_blob_message = 'blob_message'
fld_refl1d_data = 'blob_refl1d_data'
fld_json_results = 'json_results'

tbl_job_status      = 't_jobs_status'
fld_StatusTime = 'status_time'
fld_StatusName = 'status_name'

