tbl_bumps_jobs             = 't_bumps_jobs'
fld_JobID       = 'job_id'
fld_SentIP      = 'sent_ip'
fld_SentTime    = 'sent_time'
fld_Tag         = 'tag'
fld_Message     = 'message'
fld_ResultsDir  = 'results_dir'
fld_ProblemFile = 'problem_file'
fld_JobStatus   = 'job_status'
fld_EndTime     = 'end_time'

tbl_job_status      = 't_jobs_status'
fld_StatusTime = 'status_time'
fld_StatusName = 'status_name'

