# system changes
# the mysql database server runs on ncnr-r9nano (or r9 for short).
# in order to allow remote access, I've put a cooment on the line
# bins-address=127.0.0.1
# in file "/etc/mysql/mysql.conf.d/mysqld.cnf".
# after that change, I've restarted mysql with:
# "sudo /etc/init.d/mysql start"

# Using the latest long-term-support Ubuntu OS
FROM bumps_base
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "bumps_flask:app"]
# gunicorn --bind 0.0.0.0:5000 bumps_flask:app
