pip uninstall -y aniso8601
pip uninstall -y asn1crypto
pip uninstall -y certifi
pip uninstall -y cffi
pip uninstall -y chardet
pip uninstall -y click
pip uninstall -y croniter
pip uninstall -y cryptography
pip uninstall -y cycler
pip uninstall -y decorator
pip uninstall -y enum34
pip uninstall -y ez-setup
pip uninstall -y Flask
pip uninstall -y Flask-JWT-Extended
pip uninstall -y Flask-Redis
pip uninstall -y Flask-RESTful
pip uninstall -y Flask-WTF

pip uninstall -y futures
pip uninstall -y gunicorn
pip uninstall -y idna
pip uninstall -y infinity
pip uninstall -y intervals

pip uninstall -y ipaddress
pip uninstall -y isort
pip uninstall -y itsdangerous
pip uninstall -y Jinja2
pip uninstall -y MarkupSafe
pip uninstall -y matplotlib
pip uninstall -y mod-wsgi
pip uninstall -y mpld3
pip uninstall -y nose
pip uninstall -y numpy
pip uninstall -y pycparser
pip uninstall -y PyJWT
pip uninstall -y pyparsing
pip uninstall -y python-dateutil
pip uninstall -y pytz
pip uninstall -y redis
pip uninstall -y requests
pip uninstall -y scikit-learn
pip uninstall -y scipy
pip uninstall -y simplekv
pip uninstall -y six
pip uninstall -y subprocess32
pip uninstall -y urllib3
pip uninstall -y validators
pip uninstall -y Werkzeug
pip uninstall -y WTForms
